### ISSUE TITLE
Publish release

### ISSUE THREAD

**Issue by philihp** [brezinajn/openskill.kt#1]
Any thoughts on publishing a release of this? Even if it's just a no-warranty zero-dot release, if anything, it reserves the library namespace.

**Comment by brezinajn** [comment]
Sure. I'm planning to publish. I need to catch up with your implementation first though. Atm it's more than halfway there. It seems I'm gonna have some time to do it next week.

**Comment by philihp** [comment]
Awesome! I honestly expect Python's implementation will be more heavily used than Javascript. Please reach out if I can describe/explain anything I wrote.

**Comment by brezinajn** [comment]
Finally managed to properly implement optional ranking so now it's possible to have a tie.  Gonna publish it as beta version. Then add some tests and then publish it stable.

**Comment by brezinajn** [comment]
Published with jitpack
